name: rep
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- python>=3.6
- pyvcf
- cython
- h5py
- numpy
- nb_conda
- pandas>=0.23.0
- pip:
  - autopep8
  - anndata>=0.6.13
  - tables
  - scanpy
  - python-igraph
  - louvain
  - ipython
  - ipython-autotime
  - argh




