name: rep
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - xarray
  - pyarrow
  - ray
  - dask
  - numpy
  - pandas
  - pyranges
  - pytest
  - scipy
  - scikit-learn
  - joblib
  - matplotlib
  - pip:
